eureka:
    client:
        fetchRegistry: true
        registerWithEureka: true
        serviceUrl:
            defaultZone: 'http://localhost:8661/eureka/'
    instance:
        hostname: localhost
#server:
#    port: 8182
spring:
    application:
        name: service2
